### PR TITLE
Ensure 2d text can render non-text

### LINKED ISSUE #103: Non-string `Text.text` values crash `ipyforcegraph`
## Description

In [this line](https://github.com/jupyrdf/ipyforcegraph/blob/ff2af937b898e2ead158d4de2669b5b44c28dacf/js/widgets/behaviors/shapes/text.ts#L50C28-L50C28) we don't check to see if `drawOptions.text` is a string, and if it is set to something else (e.g., a number), the `ForceGraph` will crash, producing the following error.

```
text.ts:50 Uncaught TypeError: o.text.trim is not a function
```

The error seems to be not recoverable, i.e., only way to get the graph to render again is to make a new ForceGraph.  Also, errors only show up in the JavaScript Console.

## Reproduce

1. Make a dataframe for the `nodes` that has as numeric value
2. Create a `NodeShape` behavior and use `Text` as the shape
3. Assign the `.text` property using a `Column(<non-text-attribute>)`

## Expected behavior

Would expect non-text values to be cast to strings.

### PR DESCRIPTION
**Pull request by nrbgt**
## Checklist

- [x] the PR target is correct
  - `main` for releases, docs-only fixes and post-release hot-fixes
  - [x] `dev` for everything else
- [x] ran `doit lint` locally

## References

- fixes #103
- blocked by #102 

## Code changes

- [x] add reproducer test for non-text text in 2d force graph
- [ ] fix broken reproducer test

## User-facing changes

- users should be able to provide numeric columns, etc. for 2d text

## Backwards-incompatible changes
- n/a

### CODE REVIEW

**Comment by nrbgt** [comment]
Going to let this run the distance, but the fix was pretty trivial...

```diff
diff --git a/js/widgets/behaviors/shapes/text.ts b/js/widgets/behaviors/shapes/text.ts
index bf6b42d..5d3a9f0 100644
--- a/js/widgets/behaviors/shapes/text.ts
+++ b/js/widgets/behaviors/shapes/text.ts
@@ -47,7 +47,7 @@ export class TextShapeModel extends ShapeBaseModel {
       ...this._resolveFacets(options, EMark.node),
     };
 
-    if (drawOptions.text == null || !drawOptions.text.trim().length) {
+    if (drawOptions.text == null || !`${drawOptions.text}`.trim().length) {
       return;
     }
```

**Comment by sanbales** [comment]
Checked it on jupyterlite (using the `Behaviors` notebook) and can confirm that on `main` it breaks if you set the `Shape` to `Text` and set its `.text` to `Column(group)` and it doesn't with this change applied.  I think this is the reason we were using `Nunjucks` over `Column` but was never able to diagnose why `Column` would break so often.

**Review by sanbales — APPROVED** [review]
Tested on `jupyterlite` and it fixed the issue.

**Comment by nrbgt** [comment]
nice, let's just merge this one, then. release after the long weekend :fireworks: :hospital:

**Pull request merged**
