### PR TITLE
postmortem 0.4.0

### LINKED ISSUE #126: Release 0.4.0
- [ ] on `dev`
  - [x] merge all outstanding PRs
    - [x] #125
  - [x] ensure `CHANGELOG.md` is up-to-date
  - [x] ensure the versions have been bumped
    - [x] run `doit preflight:release`
  - [x] ensure a last-minute
    - [x] run `doit audit`
  - [x] validate on ReadTheDocs
    - [x] https://readthedocs.org/projects/ipyforcegraph/builds/21688860/
- [x] wait for a successful build of `dev`
  - [x] https://github.com/jupyrdf/ipyforcegraph/actions/runs/5943714430/
- [x] download the `dist` archive and unpack somewhere
- [x] create a new release through the GitHub UI
  - [x] pick a new [release] name to go with the version of real (or imaginary) [force]
    - [x] [Net](https://en.wikipedia.org/wiki/Net_force)
  - [x] paste in the relevant `CHANGELOG.md` entries
  - [x] upload the artifacts
  - [x] upload distribution to package repositories
    ```bash
    cd dist
    twine upload *.tar.gz *.whl
    npm login
    npm publish jupyrdf-jupyter-forcegraph-$VERSION.tgz
    npm logout
    ```
    - [x] https://www.npmjs.com/package/@jupyrdf/jupyter-forcegraph/v/0.4.0
    - [x] https://pypi.org/project/ipyforcegraph/0.4.0/
- [ ] postmortem
  - [x] handle `conda-forge` [feedstock] tasks
    - [x] https://github.com/conda-forge/ipyforcegraph-feedstock/pull/19
    - [x] https://anaconda.org/conda-forge/ipyforcegraph/files?version=0.4.0
  - [x] merge `dev` into `main`
  - [x] create postmortem PR from `main` targeting `dev`
    - [ ] #127
    - [x] bump to next development version
    - [x] bump the `CACHE_EPOCH`
    - [x] rebuild `yarn.lock`
    - [x] rebuild `.github/locks`
      - [ ] run `doit env:lock`
      - [ ] run `rm -rf .github/locks`
      - [ ] from a clean command prompt
        - [ ] 🐧`source envs/lock/bin/activate`
        - [ ] 🪟 `call envs/lock/Scripts/activate.bat`
      - [x] commit the new locks
    - [x] update release procedures with lessons learned in
          `.github/ISSUE_TEMPLATE/release.md`

[feedstock]: https://github.com/conda-forge/ipyforcegraph-feedstock
[force]: https://en.wikipedia.org/wiki/Category:Force
[release]: https://github.com/jupyrdf/ipyforcegraph/releases

### PR DESCRIPTION
**Pull request by nrbgt**
## Checklist

- [x] the PR target is correct
  - [ ] `main` for postmortem, docs-only fixes, and post-release hot-fixes
  - [x] `dev` for everything else
- [x] ran `doit lint` locally

## References

- fixes #126

## Code changes

  - [x] bump to next development version
    - [x] fix reproducible builds
      - [x] normalize `SOURCE_DATE_EPOCH` generation
      - [x] remove high-entropy files from `sdist`
      - [x] check in a static mapping of module ids for webpack :crying_cat_face:  
      - [x] get same builds SHA256SUMS
        - [x] local (linux)
        - [x] RTD https://readthedocs.org/api/v2/build/21701904.txt
        - [x] GHA https://github.com/jupyrdf/ipyforcegraph/actions/runs/5956837870/job/16158528925?pr=127#step:7:298
  - [x] bump the `CACHE_EPOCH`
  - [x] rebuild `yarn.lock` 
    - no change
  - [x] rebuild `.github/locks`
  - [ ] update release procedures with lessons learned in `.github/ISSUE_TEMPLATE/release.md`
    - no change

## User-facing changes

- n/a

## Backwards-incompatible changes

- n/a

### CODE REVIEW

**Comment by nrbgt** [comment]
Not sure if it's worth blocking here, but want to do a bit of looking into why our packages aren't reproducible... turns out it's _our_ code, and doesn't generate the same webpack output on a given build on CI vs e.g. my machine.

**Review by sanbales — APPROVED** [review]
I have no notes...

**Comment by nrbgt** [comment]
Thanks for the review, handling new audit findings, then will merge.

**Comment by nrbgt** [comment]
In ~30 minutes, we can also take a look at the released-this-morning `ipython 8.15`...

**Pull request merged**
